<?php

namespace App\Domain\Entities;

use DateTimeImmutable;
use InvalidArgumentException;

/**
 * Task Entity
 * 
 * Represents a task/activity in Vtiger CRM (vtiger_activity table).
 * Tasks are activities with type 'Task' that have deadlines, priorities, 
 * assignments, and status tracking for project and sales management.
 * 
 * Key characteristics:
 * - Has a defined start date and optional due date
 * - Assigned to a specific user for accountability
 * - Tracks priority levels (Low, Medium, High) for workload management
 * - Supports status workflow (Not Started → In Progress → Completed)
 * - Can be linked to other CRM entities (projects, quotes, accounts, etc.)
 * - Supports time tracking via duration fields
 * - Includes notification preferences for assignee updates
 * 
 * This entity encapsulates business rules for task management and provides
 * meaningful behavior beyond simple data storage.
 * 
 * @package App\Domain\Entities
 * @author Bolivar Delgado <bolivar.delgado@gmail.com>
 * @since 1.0.0
 * 
 * @property-read int $id Unique identifier for the task (vtiger_activity.activityid)
 * @property-read string $subject Task title or summary
 * @property-read string $activityType Type of activity (always 'Task' for this entity)
 * @property-read DateTimeImmutable $dateStart Start date of the task
 * @property-read DateTimeImmutable|null $dueDate Due date for task completion
 * @property-read string|null $timeStart Start time of the task
 * @property-read string|null $timeEnd End time of the task
 * @property-read string $status Current status of the task
 * @property-read string $priority Priority level (Low, Medium, High)
 * @property-read string|null $location Physical or virtual location
 * @property-read string|null $description Detailed task description
 * @property-read int $assignedUserId ID of user assigned to the task
 * @property-read int $createdByUserId ID of user who created the task
 * @property-read DateTimeImmutable $createdAt Task creation timestamp
 * @property-read DateTimeImmutable $updatedAt Task last update timestamp
 * @property-read int|null $relatedRecordId ID of related CRM entity
 * @property-read string|null $relatedModuleType Module type of related entity
 * @property-read bool $sendNotification Whether to notify assignee of changes
 * @property-read string|null $durationHours Duration in hours
 * @property-read string|null $durationMinutes Duration in minutes
 * 
 * @see \App\Application\UseCases\Task\CreateTaskUseCase
 * @see \App\Application\UseCases\Task\UpdateTaskUseCase
 * @see \App\Application\UseCases\Task\DeleteTaskUseCase
 * @see \App\Infrastructure\Repositories\VtigerTaskRepository
 */
class Task
{
    /**
     * Unique identifier for the task
     * 
     * Corresponds to vtiger_activity.activityid in Vtiger database.
     * Auto-generated by Vtiger's legacy ID system (MAX + 1).
     * 
     * @var int
     */
    public readonly int $id;

    /**
     * Task title or summary
     * 
     * Maximum length: 255 characters. Should be concise and descriptive
     * of the work to be performed.
     * 
     * @var string
     */
    public readonly string $subject;

    /**
     * Type of activity
     * 
     * For this entity, always 'Task'. Vtiger also supports 'Call', 'Meeting',
     * and other activity types in the same table.
     * 
     * @var string
     */
    public readonly string $activityType;

    /**
     * Start date of the task
     * 
     * The date when work on this task should begin. Cannot be null.
     * Format: YYYY-MM-DD (stored as DateTimeImmutable for manipulation).
     * 
     * @var DateTimeImmutable
     */
    public readonly DateTimeImmutable $dateStart;

    /**
     * Due date for task completion
     * 
     * The target date for completing the task. Optional but recommended
     * for time-sensitive work. Used for overdue calculations and reporting.
     * 
     * @var DateTimeImmutable|null
     */
    public readonly ?DateTimeImmutable $dueDate;

    /**
     * Start time of the task
     * 
     * Optional time component for when work should begin.
     * Format: HH:MM (24-hour format, e.g., "14:30").
     * 
     * @var string|null
     */
    public readonly ?string $timeStart;

    /**
     * End time of the task
     * 
     * Optional time component for when work should end.
     * Format: HH:MM (24-hour format, e.g., "16:00").
     * Must be >= timeStart if both are provided.
     * 
     * @var string|null
     */
    public readonly ?string $timeEnd;

    /**
     * Current status of the task
     * 
     * Valid values:
     * - "Not Started": Initial state, work has not begun
     * - "In Progress": Work is actively being done
     * - "Completed": Work is finished
     * - "Pending Input": Waiting for external input/information
     * - "Planned": Scheduled for future start
     * 
     * @var string
     */
    public readonly string $status;

    /**
     * Priority level of the task
     * 
     * Valid values:
     * - "Low": Can be deferred, not time-critical
     * - "Medium": Normal priority, standard timeline
     * - "High": Urgent, requires immediate attention
     * 
     * Used for sorting, filtering, and workload management.
     * 
     * @var string
     */
    public readonly string $priority;

    /**
     * Physical or virtual location for the task
     * 
     * Optional field for meeting addresses, conference rooms,
     * video call links, or other location information.
     * Maximum length: 150 characters.
     * 
     * @var string|null
     */
    public readonly ?string $location;

    /**
     * Detailed task description
     * 
     * Optional free-text field for additional context, requirements,
     * instructions, or notes about the task. No length limit (TEXT field).
     * 
     * @var string|null
     */
    public readonly ?string $description;

    /**
     * ID of user assigned to the task
     * 
     * References vtiger_users.id. The assigned user is responsible
     * for completing the task and receives notifications.
     * 
     * @var int
     */
    public readonly int $assignedUserId;

    /**
     * ID of user who created the task
     * 
     * References vtiger_users.id. The creator has edit/delete permissions
     * even if not assigned to the task.
     * 
     * @var int
     */
    public readonly int $createdByUserId;

    /**
     * Task creation timestamp
     * 
     * Automatically set when the task is first created.
     * Format: YYYY-MM-DD HH:MM:SS
     * 
     * @var DateTimeImmutable
     */
    public readonly DateTimeImmutable $createdAt;

    /**
     * Task last update timestamp
     * 
     * Updated every time the task is modified. Used for audit trails
     * and sorting by recent activity.
     * Format: YYYY-MM-DD HH:MM:SS
     * 
     * @var DateTimeImmutable
     */
    public readonly DateTimeImmutable $updatedAt;

    /**
     * ID of related CRM entity
     * 
     * Optional reference to another CRM record (project, quote, account,
     * potential, etc.). Enables task-context relationships.
     * 
     * @var int|null
     */
    public readonly ?int $relatedRecordId;

    /**
     * Module type of related entity
     * 
     * Examples: "Project", "Quotes", "Accounts", "Potentials", "HelpDesk".
     * Used together with relatedRecordId to establish cross-module relationships.
     * 
     * @var string|null
     */
    public readonly ?string $relatedModuleType;

    /**
     * Whether to notify assignee of changes
     * 
     * If true, the assigned user receives email/in-app notifications
     * when the task is created, updated, or deleted.
     * 
     * @var bool
     */
    public readonly bool $sendNotification;

    /**
     * Duration of the task in hours
     * 
     * Optional field for time estimation or tracking.
     * Used for workload planning and billing.
     * 
     * @var string|null
     */
    public readonly ?string $durationHours;

    /**
     * Duration of the task in minutes
     * 
     * Optional field for more granular time estimation.
     * Combined with durationHours for total duration.
     * 
     * @var string|null
     */
    public readonly ?string $durationMinutes;

    /**
     * Constructor for Task entity
     * 
     * Creates a new Task instance with validation of required fields.
     * All properties are readonly to ensure immutability after creation.
     * 
     * @param int $id Unique identifier for the task
     * @param string $subject Task title or summary
     * @param string $activityType Type of activity (should be 'Task')
     * @param DateTimeImmutable $dateStart Start date of the task
     * @param DateTimeImmutable|null $dueDate Due date for task completion (optional)
     * @param string|null $timeStart Start time of the task (optional)
     * @param string|null $timeEnd End time of the task (optional)
     * @param string $status Current status of the task
     * @param string $priority Priority level (Low, Medium, High)
     * @param string|null $location Physical or virtual location (optional)
     * @param string|null $description Detailed task description (optional)
     * @param int $assignedUserId ID of user assigned to the task
     * @param int $createdByUserId ID of user who created the task
     * @param DateTimeImmutable $createdAt Task creation timestamp
     * @param DateTimeImmutable $updatedAt Task last update timestamp
     * @param int|null $relatedRecordId ID of related CRM entity (optional)
     * @param string|null $relatedModuleType Module type of related entity (optional)
     * @param bool $sendNotification Whether to notify assignee of changes
     * @param string|null $durationHours Duration in hours (optional)
     * @param string|null $durationMinutes Duration in minutes (optional)
     * 
     * @throws InvalidArgumentException If required fields are invalid
     */
    public function __construct(
        int $id,
        string $subject,
        string $activityType,
        DateTimeImmutable $dateStart,
        ?DateTimeImmutable $dueDate,
        ?string $timeStart,
        ?string $timeEnd,
        string $status,
        string $priority,
        ?string $location,
        ?string $description,
        int $assignedUserId,
        int $createdByUserId,
        DateTimeImmutable $createdAt,
        DateTimeImmutable $updatedAt,
        ?int $relatedRecordId = null,
        ?string $relatedModuleType = null,
        bool $sendNotification = false,
        ?string $durationHours = null,
        ?string $durationMinutes = null,
    ) {
        // Validate required fields
        $this->validateId($id);
        $this->validateSubject($subject);
        $this->validateUserIds($assignedUserId, $createdByUserId);

        $this->id = $id;
        $this->subject = $subject;
        $this->activityType = $activityType;
        $this->dateStart = $dateStart;
        $this->dueDate = $dueDate;
        $this->timeStart = $timeStart;
        $this->timeEnd = $timeEnd;
        $this->status = $status;
        $this->priority = $priority;
        $this->location = $location;
        $this->description = $description;
        $this->assignedUserId = $assignedUserId;
        $this->createdByUserId = $createdByUserId;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->relatedRecordId = $relatedRecordId;
        $this->relatedModuleType = $relatedModuleType;
        $this->sendNotification = $sendNotification;
        $this->durationHours = $durationHours;
        $this->durationMinutes = $durationMinutes;
    }

    // ========================================================================
    // BASIC GETTERS (For consistent access and future extensibility)
    // ========================================================================

    /**
     * Get the unique identifier for this task
     * 
     * @return int Task ID
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Get the task subject/title
     * 
     * @return string Task subject
     */
    public function getSubject(): string
    {
        return $this->subject;
    }

    /**
     * Get the activity type
     * 
     * @return string Activity type (should be 'Task')
     */
    public function getActivityType(): string
    {
        return $this->activityType;
    }

    /**
     * Get the task start date
     * 
     * @return DateTimeImmutable Start date
     */
    public function getDateStart(): DateTimeImmutable
    {
        return $this->dateStart;
    }

    /**
     * Get the task due date
     * 
     * @return DateTimeImmutable|null Due date, or null if not set
     */
    public function getDueDate(): ?DateTimeImmutable
    {
        return $this->dueDate;
    }

    /**
     * Get the task start time
     * 
     * @return string|null Start time in HH:MM format, or null
     */
    public function getTimeStart(): ?string
    {
        return $this->timeStart;
    }

    /**
     * Get the task end time
     * 
     * @return string|null End time in HH:MM format, or null
     */
    public function getTimeEnd(): ?string
    {
        return $this->timeEnd;
    }

    /**
     * Get the current task status
     * 
     * @return string Current status
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Get the task priority level
     * 
     * @return string Priority level (Low, Medium, High)
     */
    public function getPriority(): string
    {
        return $this->priority;
    }

    /**
     * Get the task location
     * 
     * @return string|null Location, or null if not set
     */
    public function getLocation(): ?string
    {
        return $this->location;
    }

    /**
     * Get the task description
     * 
     * @return string|null Description, or null if not set
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Get the ID of the assigned user
     * 
     * @return int Assigned user ID
     */
    public function getAssignedUserId(): int
    {
        return $this->assignedUserId;
    }

    /**
     * Get the ID of the user who created the task
     * 
     * @return int Creator user ID
     */
    public function getCreatedByUserId(): int
    {
        return $this->createdByUserId;
    }

    /**
     * Get the task creation timestamp
     * 
     * @return DateTimeImmutable Creation timestamp
     */
    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * Get the task last update timestamp
     * 
     * @return DateTimeImmutable Last update timestamp
     */
    public function getUpdatedAt(): DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * Get the ID of the related CRM entity
     * 
     * @return int|null Related record ID, or null if not linked
     */
    public function getRelatedRecordId(): ?int
    {
        return $this->relatedRecordId;
    }

    /**
     * Get the module type of the related entity
     * 
     * @return string|null Related module type, or null if not linked
     */
    public function getRelatedModuleType(): ?string
    {
        return $this->relatedModuleType;
    }

    // ========================================================================
    // STATUS CHECK METHODS (Business logic for workflow)
    // ========================================================================

    /**
     * Check if task is completed
     * 
     * @return bool True if status is "Completed", false otherwise
     */
    public function isCompleted(): bool
    {
        return $this->status === 'Completed';
    }

    /**
     * Check if task is in progress
     * 
     * @return bool True if status is "In Progress", false otherwise
     */
    public function isInProgress(): bool
    {
        return $this->status === 'In Progress';
    }

    /**
     * Check if task has not been started yet
     * 
     * @return bool True if status is "Not Started", false otherwise
     */
    public function isNotStarted(): bool
    {
        return $this->status === 'Not Started';
    }

    /**
     * Check if task is pending external input
     * 
     * @return bool True if status is "Pending Input", false otherwise
     */
    public function isPendingInput(): bool
    {
        return $this->status === 'Pending Input';
    }

    /**
     * Check if task is planned for future start
     * 
     * @return bool True if status is "Planned", false otherwise
     */
    public function isPlanned(): bool
    {
        return $this->status === 'Planned';
    }

    /**
     * Check if task is overdue
     * 
     * A task is overdue if:
     * - It has a due date set
     * - The due date is in the past
     * - The task is not completed
     * 
     * @return bool True if task is overdue, false otherwise
     */
    public function isOverdue(): bool
    {
        if ($this->isCompleted() || !$this->dueDate) {
            return false;
        }

        $today = new DateTimeImmutable('today');
        return $this->dueDate < $today;
    }

    /**
     * Check if task is high priority
     * 
     * @return bool True if priority is "High", false otherwise
     */
    public function isHighPriority(): bool
    {
        return $this->priority === 'High';
    }

    /**
     * Check if task is low priority
     * 
     * @return bool True if priority is "Low", false otherwise
     */
    public function isLowPriority(): bool
    {
        return $this->priority === 'Low';
    }

    /**
     * Check if task is medium priority
     * 
     * @return bool True if priority is "Medium", false otherwise
     */
    public function isMediumPriority(): bool
    {
        return $this->priority === 'Medium';
    }

    // ========================================================================
    // AUTHORIZATION METHODS (Business rules for permissions)
    // ========================================================================

    /**
     * Check if a user can edit this task
     * 
     * Business rules:
     * - Assigned user can always edit
     * - Task creator can always edit
     * - Admin users can override (check externally)
     * 
     * @param int $userId ID of the user to check
     * @return bool True if user can edit, false otherwise
     */
    public function canBeEditedBy(int $userId): bool
    {
        return $this->assignedUserId === $userId || $this->createdByUserId === $userId;
    }

    /**
     * Check if a user can delete this task
     * 
     * Business rules:
     * - Assigned user can always delete
     * - Task creator can always delete
     * - Admin users can override (check externally)
     * 
     * @param int $userId ID of the user to check
     * @return bool True if user can delete, false otherwise
     */
    public function canBeDeletedBy(int $userId): bool
    {
        return $this->assignedUserId === $userId || $this->createdByUserId === $userId;
    }

    /**
     * Check if a user is assigned to this task
     * 
     * @param int $userId ID of the user to check
     * @return bool True if user is assigned, false otherwise
     */
    public function isAssignedTo(int $userId): bool
    {
        return $this->assignedUserId === $userId;
    }

    /**
     * Check if a user created this task
     * 
     * @param int $userId ID of the user to check
     * @return bool True if user is creator, false otherwise
     */
    public function isCreatedBy(int $userId): bool
    {
        return $this->createdByUserId === $userId;
    }

    // ========================================================================
    // UTILITY METHODS (Formatting and calculations)
    // ========================================================================

    /**
     * Get task duration in minutes
     * 
     * Combines durationHours and durationMinutes into total minutes.
     * Useful for workload planning and time tracking reports.
     * 
     * @return int|null Total duration in minutes, or null if not set
     */
    public function getDurationInMinutes(): ?int
    {
        if (!$this->durationHours && !$this->durationMinutes) {
            return null;
        }

        $hours = (int) ($this->durationHours ?? 0);
        $minutes = (int) ($this->durationMinutes ?? 0);

        return ($hours * 60) + $minutes;
    }

    /**
     * Get formatted date range for display
     * 
     * Returns a human-readable date range string.
     * Examples:
     * - "24/02/2026" (same start and due date)
     * - "24/02/2026 - 28/02/2026" (different dates)
     * 
     * @return string Formatted date range in DD/MM/YYYY format
     */
    public function getFormattedDateRange(): string
    {
        $start = $this->dateStart->format('d/m/Y');
        $end = $this->dueDate?->format('d/m/Y') ?? $start;

        return $start === $end ? $start : "$start - $end";
    }

    /**
     * Get formatted time range for display
     * 
     * Returns a human-readable time range string.
     * Examples:
     * - "All day" (no time set)
     * - "09:00 - 17:00" (specific times)
     * 
     * @return string Formatted time range in HH:MM format, or "All day"
     */
    public function getFormattedTimeRange(): string
    {
        if (!$this->timeStart && !$this->timeEnd) {
            return 'All day';
        }

        $start = $this->timeStart ?? '00:00';
        $end = $this->timeEnd ?? '23:59';

        return "$start - $end";
    }

    /**
     * Get formatted creation date for display
     * 
     * @return string Formatted date in DD/MM/YYYY HH:mm format
     */
    public function getFormattedCreatedAt(): string
    {
        return $this->createdAt->format('d/m/Y H:i');
    }

    /**
     * Get formatted update date for display
     * 
     * @return string Formatted date in DD/MM/YYYY HH:mm format
     */
    public function getFormattedUpdatedAt(): string
    {
        return $this->updatedAt->format('d/m/Y H:i');
    }

    /**
     * Get days until due date
     * 
     * Positive number = days remaining
     * Negative number = days overdue
     * Zero = due today
     * Null = no due date set
     * 
     * @return int|null Days until due, or null if no due date
     */
    public function getDaysUntilDue(): ?int
    {
        if (!$this->dueDate) {
            return null;
        }

        $today = new DateTimeImmutable('today');
        $interval = $today->diff($this->dueDate);
        
        $days = (int) $interval->format('%r%a'); // %r for sign (negative if overdue)
        
        return $days;
    }

    /**
     * Check if task is due today
     * 
     * @return bool True if due date is today, false otherwise
     */
    public function isDueToday(): bool
    {
        if (!$this->dueDate) {
            return false;
        }

        $today = new DateTimeImmutable('today');
        return $this->dueDate->format('Y-m-d') === $today->format('Y-m-d');
    }

    /**
     * Check if task is due this week
     * 
     * @return bool True if due date is within current week, false otherwise
     */
    public function isDueThisWeek(): bool
    {
        if (!$this->dueDate) {
            return false;
        }

        $today = new DateTimeImmutable('today');
        $endOfWeek = $today->modify('next sunday');
        
        return $this->dueDate >= $today && $this->dueDate <= $endOfWeek;
    }

    /**
     * Convert entity to array for API response
     * 
     * Includes all properties plus computed fields for convenience.
     * Useful for JSON serialization in controllers.
     * 
     * @return array<string, mixed> Associative array representation
     * 
     * @example
     * // In controller:
     * return response()->json($task->toArray());
     */
    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'subject' => $this->subject,
            'activityType' => $this->activityType,
            'dateStart' => $this->dateStart->format('Y-m-d'),
            'dueDate' => $this->dueDate?->format('Y-m-d'),
            'timeStart' => $this->timeStart,
            'timeEnd' => $this->timeEnd,
            'status' => $this->status,
            'priority' => $this->priority,
            'location' => $this->location,
            'description' => $this->description,
            'assignedUserId' => $this->assignedUserId,
            'createdByUserId' => $this->createdByUserId,
            'relatedRecordId' => $this->relatedRecordId,
            'relatedModuleType' => $this->relatedModuleType,
            'createdAt' => $this->createdAt->format('Y-m-d H:i:s'),
            'updatedAt' => $this->updatedAt->format('Y-m-d H:i:s'),
            'isCompleted' => $this->isCompleted(),
            'isOverdue' => $this->isOverdue(),
            'isHighPriority' => $this->isHighPriority(),
            'daysUntilDue' => $this->getDaysUntilDue(),
            'isDueToday' => $this->isDueToday(),
            'formattedDateRange' => $this->getFormattedDateRange(),
            'formattedTimeRange' => $this->getFormattedTimeRange(),
            'formattedCreatedAt' => $this->getFormattedCreatedAt(),
            'formattedUpdatedAt' => $this->getFormattedUpdatedAt(),
        ];
    }

    // ========================================================================
    // PRIVATE VALIDATION METHODS (Encapsulated business rules)
    // ========================================================================

    /**
     * Validate task ID
     * 
     * @param int $id ID to validate
     * @return void
     * @throws InvalidArgumentException If ID is invalid
     */
    private function validateId(int $id): void
    {
        if ($id <= 0) {
            throw new InvalidArgumentException('Task ID must be a positive integer');
        }
    }

    /**
     * Validate task subject
     * 
     * @param string $subject Subject to validate
     * @return void
     * @throws InvalidArgumentException If subject is invalid
     */
    private function validateSubject(string $subject): void
    {
        if (trim($subject) === '') {
            throw new InvalidArgumentException('Task subject cannot be empty');
        }
        if (strlen($subject) > 255) {
            throw new InvalidArgumentException('Task subject cannot exceed 255 characters');
        }
    }

    /**
     * Validate user IDs
     * 
     * @param int $assignedUserId Assigned user ID to validate
     * @param int $createdByUserId Creator user ID to validate
     * @return void
     * @throws InvalidArgumentException If user IDs are invalid
     */
    private function validateUserIds(int $assignedUserId, int $createdByUserId): void
    {
        if ($assignedUserId <= 0) {
            throw new InvalidArgumentException('Assigned user ID must be positive');
        }
        if ($createdByUserId <= 0) {
            throw new InvalidArgumentException('Creator user ID must be positive');
        }
    }
}