<?php

namespace App\Application\UseCases\Quote;

use App\Infrastructure\Repositories\QuoteRepository;
use App\Services\CurrentUserService;
use App\Services\VtigerActivityTracker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use InvalidArgumentException;
use RuntimeException;

/**
 * Use Case for duplicating an existing quote.
 * 
 * Creates a new quote with:
 * - New quote number (auto-generated by Vtiger)
 * - Same client, items, prices, discounts as original
 * - New creation timestamp
 * - Current user as creator
 */
class DuplicateQuoteUseCase
{
    public function __construct(
        private readonly QuoteRepository $quoteRepository,
    ) {}

    /**
     * Execute the quote duplication
     * 
     * @param int $quoteId ID of the quote to duplicate
     * @param int|null $userId ID of the user performing the duplication
     * @return int The new quote ID
     * 
     * @throws InvalidArgumentException If the quote ID is invalid or not found
     * @throws RuntimeException If duplication fails
     */
    public function execute(int $quoteId, ?int $userId = null,  string $subjectSuffix = '(Copy)'): int
    {
        if ($quoteId <= 0) {
            throw new InvalidArgumentException('Quote ID must be positive');
        }

        $userId = $userId ?? CurrentUserService::idOr(1);

        // 1. Fetch original quote with all items
        $originalQuote = $this->quoteRepository->findById($quoteId);
        
        if (!$originalQuote) {
            throw new InvalidArgumentException("Quote {$quoteId} not found");
        }

        // 2. Prepare new quote data (exclude quoteid, quoteno - will be auto-generated)
        $newQuoteData = [
            'quoteid' => $this->quoteRepository->generateQuoteId(),  // ← Nuevo ID
            'subject' => $originalQuote->subject . ' ' . $subjectSuffix,
            'potentialid' => $originalQuote->potential_name ? $this->getPotentialIdByName($originalQuote->potential_name) : null,
            'accountid' => $originalQuote->accountid,  // ← Mismo cliente
            'quotestage' => 'Draft',  // ← Resetear a Draft (configurable)
            'validtill' => $originalQuote->validtill,
            'subtotal' => $originalQuote->subtotal,
            'total' => $originalQuote->total,
            'description' => $originalQuote->description,
            'assigned_user_id' => $userId,  // ← Usuario actual como asignado
            'createdtime' => now()->format('Y-m-d H:i:s'),
            'modifiedtime' => now()->format('Y-m-d H:i:s'),
        ];

        // 3. Prepare items for insertion (reusing repository logic)
        $itemsData = [];
        if (!empty($originalQuote->items) && is_array($originalQuote->items)) {
            foreach ($originalQuote->items as $index => $item) {
                $itemsData[] = [
                    'productid' => $item['productid'] ?? null,
                    'sequence_no' => $item['sequence_no'] ?? ($index + 1),
                    'productname' => $item['productname'] ?? '',
                    'quantity' => $item['quantity'] ?? 1,
                    'listprice' => $item['listprice'] ?? 0,
                    'discount_percent' => $item['discount_percent'] ?? 0,
                    'description' => $item['description'] ?? '',
                ];
            }
        }

        // 4. Create new quote in transaction
        return DB::connection('vtiger')->transaction(function () use ($newQuoteData, $itemsData, $userId, $quoteId) {
            // Insert new quote with items (reusing existing repository method)
            $newQuoteId = $this->quoteRepository->insert($newQuoteData, $itemsData);
            
            if (!$newQuoteId) {
                throw new RuntimeException('Failed to create new quote');
            }

            // Log activity for audit trail
            $this->logActivity($newQuoteId, $userId, $quoteId);

            return $newQuoteId;
        });
    }

   /**
     * Helper to get potential ID by name (if needed for potentialid field)
     */
    private function getPotentialIdByName(string $potentialName): ?int
    {
        $potential = DB::connection('vtiger')
            ->table('vtiger_potential')
            ->where('potentialname', $potentialName)
            ->first();
        
        return $potential?->potentialid ? (int) $potential->potentialid : null;
    }

    /**
     * Log duplication activity for audit trail
     */
    private function logActivity(int $newQuoteId, int $userId, int $originalQuoteId): void
    {
        try {
            // Log creation of new quote
            VtigerActivityTracker::created(
                module: 'Quotes',
                crmid: $newQuoteId,
                userId: $userId
            );

            // Add comment on original quote mentioning the duplication
            VtigerActivityTracker::addComment(
                crmid: $originalQuoteId,
                userId: $userId,
                comment: "Quote duplicated to #{$newQuoteId}"
            );
        } catch (\Exception $e) {
            Log::error('Failed to log quote duplication activity', [
                'newQuoteId' => $newQuoteId,
                'originalQuoteId' => $originalQuoteId,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
