<?php

namespace App\Application\UseCases\Quote;

use App\Infrastructure\Repositories\QuoteRepository;
use App\Services\CurrentUserService;
use App\Services\VtigerActivityTracker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use InvalidArgumentException;
use RuntimeException;

/**
 * Use Case for duplicating an existing quote.
 * 
 * Creates a new quote with:
 * - New quote number (auto-generated by Vtiger)
 * - Same client, items, prices, discounts as original
 * - New creation timestamp
 * - Current user as creator
 */
class DuplicateQuoteUseCase
{
    public function __construct(
        private readonly QuoteRepository $quoteRepository,
    ) {}

    /**
     * Execute the quote duplication
     * 
     * @param int $quoteId ID of the quote to duplicate
     * @param int|null $userId ID of the user performing the duplication
     * @return int The new quote ID
     * 
     * @throws InvalidArgumentException If the quote ID is invalid or not found
     * @throws RuntimeException If duplication fails
     */
    public function execute(int $quoteId, ?int $userId = null, string $subjectSuffix = '(Copy)'): int
    {
        if ($quoteId <= 0) {
            throw new InvalidArgumentException('Quote ID must be positive');
        }

        $userId = $userId ?? CurrentUserService::idOr(1);
        $originalQuote = $this->quoteRepository->findById($quoteId);

        if (!$originalQuote) {
            throw new InvalidArgumentException("Quote {$quoteId} not found");
        }

        if (empty($originalQuote->accountid)) {
            throw new RuntimeException("Cannot duplicate quote {$quoteId}: missing accountid");
        }

        $itemsData = [];
        if (!empty($originalQuote->items) && is_array($originalQuote->items)) {
            foreach ($originalQuote->items as $index => $item) {
                $itemsData[] = [
                    'productid' => $item['productid'] ?? null,
                    'sequence_no' => $item['sequence_no'] ?? ($index + 1),
                    'quantity' => $item['quantity'] ?? 1,
                    'listprice' => $item['listprice'] ?? 0,
                    'discount_percent' => $item['discount_percent'] ?? 0,
                    'description' => $item['description'] ?? null,
                    'comment' => $item['comment'] ?? null,
                ];
            }
        }

        $newQuoteData = [
            'subject' => $originalQuote->subject . ' ' . $subjectSuffix,
            'potentialid' => $originalQuote->potentialid ?? null, 
            'accountid' => $originalQuote->accountid,
            'quotestage' => 'Draft',
            'validtill' => $originalQuote->validtill,
            'description' => $originalQuote->description,
            'taxtype' => $originalQuote->taxtype ?? 'individual',
            'currency_id' => $originalQuote->currency_id ?? 1,
            'conversion_rate' => $originalQuote->conversion_rate ?? 1.000,
            'discount_percent' => $originalQuote->discount_percent ?? null,
            'discount_amount' => $originalQuote->discount_amount ?? null,
            'assigned_user_id' => $userId,
        ];

        return DB::connection('vtiger')->transaction(function () use ($newQuoteData, $itemsData, $userId, $quoteId) {
            $newQuoteId = $this->quoteRepository->duplicate(
                baseData: $newQuoteData,
                itemsData: $itemsData,
                createdByUserId: $userId
            );

            if (!$newQuoteId) {
                throw new RuntimeException('Failed to create new quote');
            }

            $this->logActivity($newQuoteId, $userId, $quoteId);

            return $newQuoteId;
        });
    }

    /**
     * Helper to get potential ID by name (if needed for potentialid field)
     */
    private function getPotentialIdByName(string $potentialName): ?int
    {
        $potential = DB::connection('vtiger')
            ->table('vtiger_potential')
            ->where('potentialname', $potentialName)
            ->first();

        return $potential?->potentialid ? (int) $potential->potentialid : null;
    }

    /**
     * Log duplication activity for audit trail
     */
    private function logActivity(int $newQuoteId, int $userId, int $originalQuoteId): void
    {
        try {
            // Log creation of new quote
            VtigerActivityTracker::created(
                module: 'Quotes',
                crmid: $newQuoteId,
                userId: $userId
            );

            // Add comment on original quote mentioning the duplication
            VtigerActivityTracker::addComment(
                crmid: $originalQuoteId,
                userId: $userId,
                comment: "Quote duplicated to #{$newQuoteId}"
            );
        } catch (\Exception $e) {
            Log::error('Failed to log quote duplication activity', [
                'newQuoteId' => $newQuoteId,
                'originalQuoteId' => $originalQuoteId,
                'error' => $e->getMessage(),
            ]);
        }
    }
}
