<?php

namespace App\Infrastructure\Repositories;

use App\Application\Contracts\GoogleDriveServiceInterface;
use App\Application\Repositories\AttachmentRepositoryInterface;
use App\Domain\Entities\Attachment;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;

/**
 * Class VtigerAttachmentRepository
 * 
 * Vtiger-specific implementation of the AttachmentRepositoryInterface.
 * 
 * This repository handles attachment persistence operations for the Vtiger CRM
 * system, integrating with Google Drive for file storage while maintaining
 * metadata and relationships in Vtiger database tables.
 * 
 * Implementation details:
 * - File storage: Files are uploaded to Google Drive via GoogleDriveService
 * - Metadata persistence: Attachment metadata stored in vtiger_attachments table
 * - Audit tracking: Creation/modification data stored in vtiger_crmentity table
 * - Relationship management: Module-record associations stored in vtiger_seattachmentsrel
 * - Soft delete: Deletion marks records as deleted in vtiger_crmentity without
 *   removing from Google Drive (preserves audit trail and allows restoration)
 * - Transaction safety: All write operations wrapped in database transactions
 *   to ensure consistency across multiple table updates
 * 
 * Database tables involved:
 * - vtiger_crmentity: Core entity metadata, audit fields, soft delete flag
 * - vtiger_attachments: File-specific metadata (name, type, size, Google Drive ID)
 * - vtiger_seattachmentsrel: Many-to-many relationship between CRM records and attachments
 * 
 * Google Drive integration:
 * - Upload: Files uploaded via GoogleDriveService::uploadFile() returning file metadata
 * - Listing: Files retrieved via GoogleDriveService::listFiles() for URL generation
 * - Deletion: Files removed via GoogleDriveService::deleteFile() when attachment deleted
 * - URL generation: Web content and view URLs obtained from Google Drive API responses
 * 
 * ID generation strategy:
 * - Vtiger legacy pattern: New CRM IDs generated by fetching MAX(crmid) + 1
 * - This approach ensures compatibility with Vtiger's auto-increment emulation
 * - Note: In high-concurrency environments, consider using database sequences
 *   or application-level ID generators with proper locking
 * 
 * @package App\Infrastructure\Repositories
 * @author Bolivar Delgado <bolivar.delagado@gmail.com>
 * @version 1.0.0
 * 
 * @implements AttachmentRepositoryInterface
 * @see AttachmentRepositoryInterface For the contract this class implements
 * @see GoogleDriveService For the external file storage service integration
 * @see Attachment For the domain entity returned by repository methods
 */
class VtigerAttachmentRepository implements AttachmentRepositoryInterface
{
    

    /**
     * VtigerAttachmentRepository constructor.
     * 
     * Injects the GoogleDriveService dependency via constructor injection.
     * This enables dependency inversion, facilitating unit testing with mock
     * implementations and promoting loose coupling between the repository
     * and external storage service.
     * 
     * @param GoogleDriveService $driveService The Google Drive service instance
     *                                          for handling file operations.
     * 
     * @return void
     */
    public function __construct(
        private readonly GoogleDriveServiceInterface $driveService
    ) {}

    /**
     * Upload and persist a new attachment file.
     * 
     * Implementation details:
     * - Executes all database operations within a transaction to ensure
     *   atomicity across vtiger_crmentity, vtiger_attachments, and
     *   vtiger_seattachmentsrel table updates
     * - Generates new CRM ID using Vtiger legacy pattern: MAX(crmid) + 1
     * - Uploads file to Google Drive first, then persists metadata only
     *   if upload succeeds (prevents orphaned database records)
     * - Uses authenticated user ID for audit fields (smcreatorid, smownerid)
     * - Sets entity type to 'Documents' in vtiger_crmentity for consistency
     *   with Vtiger's attachment handling conventions
     * - Stores Google Drive file ID in vtiger_attachments.path field
     * - Creates relationship record in vtiger_seattachmentsrel to link
     *   attachment to target module and record
     * 
     * Error handling:
     * - If Google Drive upload fails, transaction rolls back and exception
     *   propagates to caller
     * - If any database insert fails, transaction rolls back and previously
     *   uploaded file remains in Google Drive (cleanup job recommended)
     * - Validation of input parameters should be performed by calling use case
     *   before invoking this method
     * 
     * @inheritDoc
     * 
     * @throws \RuntimeException If Google Drive upload fails or database
     *                           transaction cannot be completed
     * @throws \InvalidArgumentException If input parameters are invalid
     * @throws \Exception If any unexpected error occurs during upload process
     * 
     * @internal ID generation uses MAX(crmid) + 1 pattern which may have
     *           race conditions in high-concurrency environments
     */
    public function upload(
        UploadedFile $file,
        string $module,
        int $recordId,
        int $authenticatedUserId,
        ?string $description = null
    ): Attachment {
        return DB::connection('vtiger')->transaction(function () use ($file, $module, $recordId, $authenticatedUserId, $description) {
            // Upload to Google Drive
            $driveResult = $this->driveService->uploadFile($file, $module, $recordId);

            // Insert into vtiger_crmentity
            $maxCrmid = DB::connection('vtiger')
                ->table('vtiger_crmentity')
                ->max('crmid');

            $crmid = $maxCrmid ? $maxCrmid + 1 : 1;

            DB::connection('vtiger')->table('vtiger_crmentity')->insert([
                'crmid' => $crmid,
                'smcreatorid' => $authenticatedUserId,
                'smownerid' => $authenticatedUserId,
                'setype' => 'Documents',
                'description' => $description,
                'createdtime' => now()->format('Y-m-d H:i:s'),
                'modifiedtime' => now()->format('Y-m-d H:i:s'),
                'deleted' => 0,
            ]);

            // Insert into vtiger_attachments
            DB::connection('vtiger')->table('vtiger_attachments')->insert([
                'attachmentsid' => $crmid,
                'name' => $driveResult['name'],
                'description' => $description,
                'type' => $driveResult['mime_type'],
                'path' => $driveResult['id'],
                'filesize' => $driveResult['size'] ?? 0,
            ]);

            // Relate to module
            DB::connection('vtiger')->table('vtiger_seattachmentsrel')->insert([
                'crmid' => $recordId,
                'attachmentsid' => $crmid,
            ]);

            // Return entity
            return new Attachment(
                id: $crmid,
                name: $driveResult['name'],
                description: $description,
                mimeType: $driveResult['mime_type'],
                size: $driveResult['size'] ?? 0,
                googleDriveId: $driveResult['id'],
                url: $driveResult['url'],
                viewUrl: $driveResult['view_url'],
                relatedRecordId: $recordId,
                module: $module,
                createdAt: new \DateTimeImmutable()
            );
        });
    }

    /**
     * Retrieve all attachments related to a specific module and record.
     * 
     * Implementation details:
     * - First queries vtiger_seattachmentsrel to get attachment IDs linked
     *   to the specified record, enabling efficient filtering before joining
     * - Returns empty array immediately if no related attachments found,
     *   avoiding unnecessary database queries
     * - Joins vtiger_attachments with vtiger_crmentity to filter out
     *   soft-deleted attachments (deleted = 0)
     * - For each attachment, queries Google Drive API to retrieve current
     *   file metadata including webContentLink and webViewLink for URL generation
     * - Uses collect() helper for functional-style filtering of Google Drive
     *   results to match attachment by Google Drive ID
     * - Silently skips attachments that cannot be found in Google Drive
     *   (may indicate orphaned database records or permission issues)
     * - Constructs Attachment entities with URLs from Google Drive API
     *   response rather than storing URLs in database (ensures freshness)
     * 
     * Performance considerations:
     * - Makes one Google Drive API call per attachment; for records with
     *   many attachments, consider batching or caching strategies
     * - Google Drive API rate limits may affect response time; implement
     *   exponential backoff in GoogleDriveService if needed
     * - Database queries use indexed fields (crmid, attachmentsid) for
     *   efficient lookups
     * 
     * Error handling:
     * - Catches and suppresses exceptions from Google Drive API calls to
     *   prevent single file issues from breaking entire attachment list
     * - Logs should be added in production to track skipped files for
     *   maintenance and cleanup purposes
     * 
     * @inheritDoc
     * 
     * @return array<int, Attachment> Array of Attachment entities with
     *                                current Google Drive URLs, or empty
     *                                array if none found
     * 
     * @throws \RuntimeException If database queries fail or connection
     *                           to Vtiger database is lost
     */
    public function findByModuleAndRecord(string $module, int $recordId): array
    {
        // Get related attachment IDs
        $attachmentIds = DB::connection('vtiger')
            ->table('vtiger_seattachmentsrel')
            ->where('crmid', $recordId)
            ->pluck('attachmentsid')
            ->toArray();

        if (empty($attachmentIds)) {
            return [];
        }

        // Get attachment details
        $attachments = DB::connection('vtiger')
            ->table('vtiger_attachments')
            ->join('vtiger_crmentity', 'vtiger_attachments.attachmentsid', '=', 'vtiger_crmentity.crmid')
            ->whereIn('vtiger_attachments.attachmentsid', $attachmentIds)
            ->where('vtiger_crmentity.deleted', 0)
            ->select(
                'vtiger_attachments.attachmentsid',
                'vtiger_attachments.name',
                'vtiger_attachments.description',
                'vtiger_attachments.type as mime_type',
                'vtiger_attachments.path as google_drive_id',
                'vtiger_attachments.filesize as size',
                'vtiger_crmentity.createdtime'
            )
            ->get();

        // Get Google Drive URLs for each file
        $result = [];
        foreach ($attachments as $att) {
            try {
                $files = $this->driveService->listFiles($module, $recordId);
                $file = collect($files)->first(fn($f) => $f->id === $att->google_drive_id);
                
                if ($file) {
                    $result[] = new Attachment(
                        id: $att->attachmentsid,
                        name: $att->name,
                        description: $att->description,
                        mimeType: $att->mime_type,
                        size: $att->size,
                        googleDriveId: $att->google_drive_id,
                        url: $file->webContentLink ?? $file->webViewLink,
                        viewUrl: $file->webViewLink,
                        relatedRecordId: $recordId,
                        module: $module,
                        createdAt: new \DateTimeImmutable($att->createdtime)
                    );
                }
            } catch (\Exception $e) {
                // Skip files that cannot be found in Drive
                continue;
            }
        }

        return $result;
    }

    /**
     * Delete an attachment and its associated file.
     * 
     * Implementation details:
     * - Executes all operations within a transaction to ensure atomicity
     *   across permission check, Google Drive deletion, and database update
     * - Verifies attachment exists and is not already soft-deleted before
     *   proceeding (prevents redundant operations and provides clear error)
     * - Retrieves Google Drive file ID from vtiger_attachments.path before
     *   marking record as deleted (ensures ID is available for Drive API call)
     * - Deletes file from Google Drive via GoogleDriveService before updating
     *   database (prevents orphaned files if database update fails)
     * - Performs soft delete by setting deleted = 1 in vtiger_crmentity
     *   rather than removing record (preserves audit trail and allows
     *   potential restoration via admin tools)
     * - Updates modifiedtime timestamp to track when deletion occurred
     * - Returns boolean success indicator; exceptions propagate for
     *   unexpected errors
     * 
     * Permission handling:
     * - Current implementation checks only that attachment exists and is
     *   not deleted; production deployments should add authorization logic
     *   to verify authenticated user has permission to delete the attachment
     *   (e.g., is owner, has admin role, or has module-level delete permission)
     * 
     * Cleanup considerations:
     * - If Google Drive deletion fails but database update succeeds, file
     *   remains in Drive but is inaccessible via CRM (orphaned file)
     * - Consider implementing periodic cleanup job to identify and remove
     *   orphaned files by comparing vtiger_attachments with Google Drive
     *   contents
     * - Soft-deleted records accumulate in database; consider archival
     *   strategy for records older than retention period
     * 
     * @inheritDoc
     * 
     * @return bool True if deletion was successful, false if attachment
     *              was not found or already deleted
     * 
     * @throws \RuntimeException If database transaction fails or Google
     *                           Drive deletion encounters an error
     * @throws \Exception If attachment not found or already deleted, or
     *                    if any unexpected error occurs during deletion
     */
    public function delete(int $attachmentId, int $authenticatedUserId): bool
    {
        return DB::connection('vtiger')->transaction(function () use ($attachmentId, $authenticatedUserId) {
            // Verify user has permission to delete
            $attachment = DB::connection('vtiger')
                ->table('vtiger_crmentity')
                ->where('crmid', $attachmentId)
                ->where('deleted', 0)
                ->first();

            if (!$attachment) {
                throw new \Exception('Attachment not found or already deleted');
            }

            // Get Google Drive ID before deleting
            $driveAttachment = DB::connection('vtiger')
                ->table('vtiger_attachments')
                ->where('attachmentsid', $attachmentId)
                ->first();

            if ($driveAttachment) {
                // Delete from Google Drive
                $this->driveService->deleteFile($driveAttachment->path);
            }

            // Mark as deleted in vtiger_crmentity
            DB::connection('vtiger')
                ->table('vtiger_crmentity')
                ->where('crmid', $attachmentId)
                ->update([
                    'deleted' => 1,
                    'modifiedtime' => now()->format('Y-m-d H:i:s'),
                ]);

            return true;
        });
    }
}